#!/usr/bin/env python3
"""Build Google My Maps-ready CSV + Markdown table from Japan-2026.csv saved places.

Categories + colors:
  🍜 Dining          #E63946 red
  ☕ Cafe/Kissaten   #B5651D brown
  🏯 Sightseeing     #1D4ED8 blue
  🛍️  Shopping        #16A34A green
  🏨 Hotel           #7C3AED purple
  🌃 Nightlife       #DB2777 pink
  🚉 Transit         #6B7280 gray
  🎌 Cultural        #C9A227 gold
"""

import csv
import os

CATEGORY_META = {
    "Dining":      {"emoji": "🍜",  "color": "#E63946"},
    "Cafe":        {"emoji": "☕",  "color": "#B5651D"},
    "Sightseeing": {"emoji": "🏯",  "color": "#1D4ED8"},
    "Shopping":    {"emoji": "🛍️",  "color": "#16A34A"},
    "Hotel":       {"emoji": "🏨",  "color": "#7C3AED"},
    "Nightlife":   {"emoji": "🌃",  "color": "#DB2777"},
    "Transit":     {"emoji": "🚉",  "color": "#6B7280"},
    "Cultural":    {"emoji": "🎌",  "color": "#C9A227"},
}

# Master dict: title -> (city, category, address, note)
# Note format: "Station: <station>. <one tip>."
DB = {
    # --- Tokyo: Pizza / Dining ---
    "The Pizza Bar On 38th": ("Tokyo", "Dining",
        "2-1-1 Nihonbashi-Muromachi, Chuo, Tokyo (Mandarin Oriental, 38F)",
        "Mitsukoshimae Stn (1 min). Eight-seat counter, reservations open 1 month ahead — book the second the slot opens."),
    # --- Kagoshima ---
    "ぎょうざのみっちー 中央駅店": ("Kagoshima", "Dining",
        "1-1 Chuocho, Kagoshima 890-0053",
        "Kagoshima-Chuo Stn (2 min). Order the iron-plate gyoza set; cash only, opens 17:00."),
    "Kagoshima Furusato Yataimura Area Li-Ka": ("Kagoshima", "Dining",
        "6-4 Chuocho, Kagoshima (Li-Ka 1920 B1)",
        "Kagoshima-Chuo Stn (3 min). 25 yatai under one roof — perfect for the group; arrive by 18:00 to claim seats."),
    "Kagoshima Furusato Yataimura BUSCHIKA": ("Kagoshima", "Dining",
        "6-4 Chuocho, Kagoshima (Li-Ka 1920 B1)",
        "Kagoshima-Chuo Stn (3 min). Kurobuta shabu stall — Brady safe (no egg); ask for soy-based dashi for Cody/JJ."),
    # --- Tokyo: Sushi / Beef ---
    "Otachidokoro Sushi Ki": ("Tokyo", "Dining",
        "5-9-19 Ginza, Chuo, Tokyo",
        "Ginza Stn (3 min). Standing-only Edomae omakase ~¥3000; line forms 15 min before open."),
    "Gyukatsu Motomura": ("Tokyo", "Dining",
        "3-18-10 Shinbashi, Minato, Tokyo (basement)",
        "Shinbashi Stn (4 min). Original branch — sear the wagyu cutlet 10 sec/side on the lava stone; expect 30-min queue."),
    # --- Kyoto: Dining ---
    "Kyoto Tonkatsu Katsuda Shijokarasuma": ("Kyoto", "Dining",
        "21 Shijoagaru Naginatabokocho, Shimogyo-ku, Kyoto",
        "Karasuma Stn (1 min). Lunch sets ¥1500 with miso/red-miso choice; line by 11:30."),
    "Gion Duck Noodles Arashiyama": ("Kyoto", "Dining",
        "20-1 Sagatenryuji Tsukurimichicho, Ukyo-ku, Kyoto",
        "Saga-Arashiyama Stn (5 min). Duck shoyu ramen — heads-up Cody/JJ: broth is poultry-based (no fish dashi)."),
    "Steak Otsuka": ("Kyoto", "Dining",
        "46-1 Sagatenryuji Susukinobabacho, Ukyo-ku, Kyoto",
        "Saga-Arashiyama Stn (4 min). Wagyu lunch set ¥3800; reserve same-morning by phone, no walk-ins after 11:30."),
    "Kijurou": ("Kyoto", "Dining",
        "47 Sagatenryuji Tsukurimichicho, Ukyo-ku, Kyoto",
        "Saga-Arashiyama Stn (3 min). Hidden tempura counter on bamboo path; the anago course is the play."),
    "Arashiyama Itsukichaya": ("Kyoto", "Dining",
        "Sagaogurayama Tabuchiyama-cho, Ukyo-ku, Kyoto",
        "Saga-Arashiyama Stn (10 min). BOOKED May 26 13:45 post-Hozugawa boat — kaiseki w/ river views."),
    "Yudofu Sagano": ("Kyoto", "Dining",
        "45 Sagatenryuji Susukinobabacho, Ukyo-ku, Kyoto",
        "Saga-Arashiyama Stn (5 min). Tofu kaiseki in a temple garden — 100% Brady & Cody/JJ safe (kombu dashi)."),
    "PIZZERIA MAMA": ("Atami", "Dining",
        "11-1 Tawarahoncho, Atami, Shizuoka",
        "Atami Stn (3 min). Family-run wood-fired Napoletana — a sane antidote between ryokan kaiseki nights."),
    # --- Atami / Izu ---
    "MOA Museum of Art": ("Atami", "Sightseeing",
        "26-2 Momoyamacho, Atami, Shizuoka",
        "Atami Stn + bus 8 min. Hilltop museum w/ moving escalator tunnel; National Treasures wing free w/ ticket."),
    "Kiunkaku": ("Atami", "Sightseeing",
        "4-2 Showacho, Atami, Shizuoka",
        "Atami Stn (15 min walk). 1919 villa-turned-ryokan museum; ¥610 — go early AM, near-empty."),
    "Atami Castle": ("Atami", "Sightseeing",
        "1993 Sokoyama, Atami, Shizuoka",
        "Atami Stn + ropeway. Skip the museum, ride the rooftop deck for the bay panorama."),
    "Kawana Dolphin Beach": ("Izu", "Sightseeing",
        "1064 Kawana, Ito, Shizuoka",
        "Kawana Stn (15 min walk). Quiet cove for tide-pool browsing; weekday mornings only."),
    "Mt. Omuro Summit": ("Izu", "Sightseeing",
        "1317-5 Futo, Ito, Shizuoka",
        "Izu-Kogen Stn + bus 15 min. Take the chairlift — the crater rim walk is the photo op."),
    "Okuno Dam": ("Izu", "Sightseeing",
        "Ikeshiroyama, Ito, Shizuoka",
        "Izu-Kogen Stn + 25 min by car. Lakeside cherry walk; SUP rentals on weekends."),
    "Tatadohama beach": ("Izu", "Sightseeing",
        "Tatado, Shimoda, Shizuoka",
        "Izukyu-Shimoda Stn + bus 15 min. Best surf beach in southern Izu — sunset session > swim."),
    "Perry Road": ("Izu", "Sightseeing",
        "3 Chome Shimoda, Shizuoka",
        "Izukyu-Shimoda Stn (10 min). Willow-lined canal walk through Edo merchant houses; pop into Babanote café."),
    "Shimoda Ropeway Summit Station (Nesugatayama Station)": ("Izu", "Transit",
        "1-3-2 Higashihongo, Shimoda, Shizuoka",
        "Izukyu-Shimoda Stn (1 min). 4-min ropeway to bay viewpoint; first car at 8:45."),
    "Cape Tsumekizaki Lighthouse.": ("Izu", "Sightseeing",
        "Suzaki, Shimoda, Shizuoka",
        "Izukyu-Shimoda Stn + bus 30 min. Dramatic basalt cliffs; bring wind layer."),
    "Shirahama Central Beach": ("Izu", "Sightseeing",
        "Shirahama, Shimoda, Shizuoka",
        "Izukyu-Shimoda Stn + bus 10 min. White-sand swim beach; arrive before 10am for parking."),
    "Sotoura Beach": ("Izu", "Sightseeing",
        "2-23 Sotoura, Shimoda, Shizuoka",
        "Izukyu-Shimoda Stn + bus 7 min. Calm horseshoe bay — best swimming with the group."),
    "Izu Oceanic Park": ("Izu", "Sightseeing",
        "865-1 Futo, Ito, Shizuoka",
        "Futo Stn + bus 20 min. Dive site + cliff garden; Saboten cafe inside has ocean view."),
    "Tajima Falls": ("Izu", "Sightseeing",
        "Yugashima, Izu, Shizuoka",
        "Shuzenji Stn + bus 30 min. Triple-tier waterfall hike; 20-min boardwalk loop."),
    "Kadowakisaki Lighthouse": ("Izu", "Sightseeing",
        "Kadowaki, Ito, Shizuoka",
        "Izu-Kogen Stn + bus. Suspension bridge over basalt cliffs — go at golden hour."),
    "Jogasaki Coast": ("Izu", "Sightseeing",
        "Yawatano, Ito, Shizuoka",
        "Jogasaki-Kaigan Stn (25 min walk). 9km cliff trail; Hashidate suspension bridge mile is the highlight."),
    "Hotel Grand Bach Atami crescendo": ("Atami", "Hotel",
        "16-3 Higashikaigancho, Atami, Shizuoka",
        "Atami Stn (8 min). Booked. Check rooftop onsen 6-7am for Sagami Bay sunrise."),
    # --- Tokyo: more dining ---
    "Curry Station Niagara": ("Tokyo", "Dining",
        "3-22-13 Hiroo, Shibuya, Tokyo",
        "Hiroo Stn (5 min). Train-themed curry shop — plates arrive by mini locomotive; cash only."),
    "PokéPark Kanto": ("Tokyo", "Sightseeing",
        "Yomiuri Land, 4015-1 Yanokuchi, Inagi, Tokyo",
        "Yomiuriland-mae Stn. Opens spring 2026 — book timed-entry the moment it goes live."),
    "Takayamashichiten Hanbaikasugaten": ("Nara", "Dining",
        "1F, 16 Kasuganocho, Nara",
        "Kintetsu-Nara Stn + bus 10 min. Casual lunch stop near Kasuga Shrine; soba sets ¥1100."),
    "Men-ya Inoichi Hanare": ("Kyoto", "Dining",
        "1F Karasuma Bldg, 511 Tearaimizucho, Shimogyo, Kyoto",
        "Shijo Stn (3 min). Michelin Bib ramen — golden chicken broth (Cody/JJ safe, ask no fish topping)."),
    # --- Tokyo Shopping ---
    "TAKEO KIKUCHI": ("Tokyo", "Shopping",
        "Shibuya Parco 4F, 15-1 Udagawacho, Shibuya, Tokyo",
        "Shibuya Stn (5 min). Japanese tailoring — main flagship inside Parco."),
    "Kapital": ("Tokyo", "Shopping",
        "2-20-2 Higashi, Shibuya, Tokyo",
        "Ebisu Stn (10 min). Three Ebisu storefronts within a block — start at 'Legs', end at 'Country'."),
    "mont-bell Shibuya": ("Tokyo", "Shopping",
        "11-3 Udagawacho, Shibuya, Tokyo",
        "Shibuya Stn (5 min). Cheaper than US prices; tax-free desk on 1F (passport needed)."),
    "mont-bell Okachimachi Store": ("Tokyo", "Shopping",
        "5-10-5 Ueno, Taito, Tokyo",
        "Okachimachi Stn (3 min). Largest Tokyo branch — full UL Pack lineup in stock."),
    "mont-bell Tokyo Kyobashi": ("Tokyo", "Shopping",
        "3-1-1 Kyobashi, Chuo, Tokyo",
        "Kyobashi Stn (1 min). Quietest of the three; great for trying-on without crowds."),
    "MOMOTARO JEANS Aoyama": ("Tokyo", "Shopping",
        "5-8-5 Minami-Aoyama, Minato, Tokyo",
        "Omotesando Stn (5 min). Selvedge denim from Kojima — they hem on-site in 30 min."),
    "KANEKO GANKYO-TEN Tokyo Solamachi": ("Tokyo", "Shopping",
        "Tokyo Solamachi 4F, 1-1-2 Oshiage, Sumida, Tokyo",
        "Oshiage Stn (1 min). Handmade frames; lenses cut in 2hr — drop off, then climb Skytree."),
    "OWNDAYS 上野マルイ店": ("Tokyo", "Shopping",
        "Marui Ueno 5F, 6-15-1 Ueno, Taito, Tokyo",
        "Ueno Stn (1 min). Same-day prescription glasses ~¥8000 incl. lenses."),
    "HANDS Ginza": ("Tokyo", "Shopping",
        "Marronnier Gate Ginza 2, 3-2-1 Ginza, Chuo, Tokyo",
        "Ginza-itchome Stn (1 min). Best souvenir floor — kitchen + stationery levels are mandatory."),
    "Sekaido Shinjuku": ("Tokyo", "Shopping",
        "3-1-1 Shinjuku, Shinjuku, Tokyo",
        "Shinjuku-sanchome Stn (3 min). 5 floors of art supplies — the basement washi paper is the move."),
    "つば屋庖丁店 | CUTLERY TSUBAYA": ("Tokyo", "Shopping",
        "3-7-2 Nishi-Asakusa, Taito, Tokyo",
        "Tawaramachi Stn (5 min). Kappabashi knife shop — they engrave your name in kanji free."),
    # --- Tokyo Nightlife / Cafes ---
    "music bar Beatle momo": ("Kyoto", "Nightlife",
        "326-1 Oyamamotomachi, Higashiyama, Kyoto",
        "Sanjo Stn (5 min). Beatles vinyl bar; ¥1500 cover + 1 drink; closes 1am."),
    "Coffee PUNKTO": ("Tokyo", "Cafe",
        "3-1-12 Shibuya, Shibuya, Tokyo",
        "Shibuya Stn (8 min). Single-origin pour-over hidden in a Cat St alley; closes 5pm."),
    "Owl Village Cafe Harajuku": ("Tokyo", "Cafe",
        "4-28-22 Jingumae, Shibuya, Tokyo",
        "Meiji-jingumae Stn (3 min). Reserve online; 1hr slot ¥2200 incl. drink — animal welfare ok-ish."),
    "Shisha Cafe tone.": ("Tokyo", "Cafe",
        "1-23-12 Higashi-Ueno, Taito, Tokyo",
        "Ueno Stn (5 min). Late-night hookah lounge; 2hr ¥3500."),
    "Chiku Chiku Cafe": ("Tokyo", "Cafe",
        "B1, 3-30-7 Jingumae, Shibuya, Tokyo",
        "Omotesando Stn (3 min). Sewing-cafe concept — cute Brady-friendly desserts (egg-free options exist, ask)."),
    "DyCE Global Board Game Cafe": ("Tokyo", "Cafe",
        "B1, 1-19-2 Kabukicho, Shinjuku, Tokyo",
        "Shinjuku Stn (8 min). 1000+ games incl. English titles; ¥600/hr."),
    "Cafe Legato": ("Tokyo", "Cafe",
        "5F, 1-22-6 Jinnan, Shibuya, Tokyo",
        "Shibuya Stn (5 min). Hidden 5F resto-cafe w/ city view; killer parfaits."),
    "GOOD COFFEE FARMS Cafe & Bar": ("Tokyo", "Cafe",
        "2-7-9 Ebisu, Shibuya, Tokyo",
        "Ebisu Stn (3 min). Guatemala farm-direct; the cascara soda is the surprise win."),
    "NORTHERNWOOD GINZA": ("Tokyo", "Cafe",
        "5-9-1 Ginza, Chuo, Tokyo",
        "Ginza Stn (3 min). Cozy Ginza pause — smoked-cheese sando + coffee."),
    "Cafe＆Bar Living Room 浅草": ("Tokyo", "Cafe",
        "2-6-1 Asakusa, Taito, Tokyo",
        "Asakusa Stn (5 min). Sofa lounge near Senso-ji — a calm break mid-day."),
    "COFFEE&BEER HI-CONDITION Asakusa": ("Tokyo", "Cafe",
        "1-25-13 Asakusa, Taito, Tokyo",
        "Asakusa Stn (3 min). Espresso AM, craft beer flips PM at 4 — same counter."),
    "GEISHA COFFEE ゲイシャコーヒー": ("Tokyo", "Cafe",
        "2-5-2 Asakusa, Taito, Tokyo",
        "Asakusa Stn (4 min). Geisha-bean specialist; ¥1500 cup is the splurge."),
    "KIELO COFFEE ASAKUSA": ("Tokyo", "Cafe",
        "1-15-3 Asakusa, Taito, Tokyo",
        "Asakusa Stn (3 min). Finnish-style — the rye-cinnamon bun pairs with Nordic roast."),
    "ART CAFE T8 ASAKUSA ‐Japanese Cultural Art Experience‐": ("Tokyo", "Cultural",
        "2-7-13 Nishi-Asakusa, Taito, Tokyo",
        "Tawaramachi Stn (3 min). Kimono / calligraphy / tea workshops — book a 90-min slot online."),
    "pignic cafe Asakusa【mini pig cafe】": ("Tokyo", "Cafe",
        "1-29-2 Asakusa, Taito, Tokyo",
        "Asakusa Stn (3 min). 30-min slot ¥1500; reserve online same-day."),
    # --- Tokyo Beef branches ---
    "Gyukatsu Motomura Shibuya Branch": ("Tokyo", "Dining",
        "3-18-10 Shibuya, Shibuya, Tokyo (basement)",
        "Shibuya Stn (5 min). Same lava-stone wagyu cutlet — Shibuya queue is faster than Shinbashi."),
    "Gyukatsu - motomura": ("Tokyo", "Dining",
        "B1, 3-29-2 Shinjuku, Shinjuku, Tokyo",
        "Shinjuku-sanchome Stn (2 min). Shinjuku branch; 30 min line at lunch."),
    "Yoshinoya Shibuya 109 Mae": ("Tokyo", "Dining",
        "2-29-7 Dogenzaka, Shibuya, Tokyo",
        "Shibuya Stn (1 min). 24-hr beef bowls; the niku-dakusu (extra meat) is the order."),
    "Yoshinoya Shinjuku Keio mall": ("Tokyo", "Dining",
        "Keio Mall, 1-1-4 Nishi-Shinjuku, Tokyo",
        "Shinjuku Stn (1 min). Underground mall location — fast escape between tasks."),
    "Yoshinoya Yaechika Shop": ("Tokyo", "Dining",
        "Yaechika 2-1, 2-1 Yaesu, Chuo, Tokyo",
        "Tokyo Stn Yaesu side. Pre-Shinkansen ¥500 lunch."),
    "Yoshinoya": ("Tokyo", "Dining",
        "Tokyo (saved location)",
        "Pre-pinned generic Yoshinoya — confirm exact branch before going."),
    "Yoshinoya Asakusa": ("Tokyo", "Dining",
        "1-2-3 Hanakawado, Taito, Tokyo",
        "Asakusa Stn (1 min). Right by Senso-ji — easy breakfast gyudon."),
    "Omotesando Ukai Tei": ("Tokyo", "Dining",
        "GYRE 5F, 5-10-1 Jingumae, Shibuya, Tokyo",
        "Omotesando Stn (3 min). Teppanyaki splurge — Brady-safe egg-free option exists, just call ahead."),
    "Shibuya Kappo Sancho": ("Tokyo", "Dining",
        "B1, 1-12-7 Dogenzaka, Shibuya, Tokyo",
        "Shibuya Stn (5 min). Hidden kappo counter — chef's choice ¥6800; reserve."),
    "Shabusen Ginza Ten": ("Tokyo", "Dining",
        "Core Ginza B2/B3, 5-8-20 Ginza, Chuo, Tokyo",
        "Ginza Stn (1 min). Counter shabu-shabu — pick kombu broth for Cody/JJ."),
    "GINZA kappou ukai nikusho": ("Tokyo", "Dining",
        "Ginza Six 6F, 6-10-1 Ginza, Chuo, Tokyo",
        "Ginza Stn (3 min). Wagyu kappo inside Ginza Six; lunch is the value."),
    "Kuroge Wagyu Ichinoya Asakusa": ("Tokyo", "Dining",
        "1-39-13 Asakusa, Taito, Tokyo",
        "Asakusa Stn (3 min). Kuroge wagyu yakiniku set — order the misuji cut."),
    "Kukurihime Coffee Asakusa cafe": ("Tokyo", "Cafe",
        "2-7-13 Asakusa, Taito, Tokyo",
        "Asakusa Stn (5 min). Hand-drip + matcha tiramisu; quiet morning spot."),
    "Asakusa Gyukatsu": ("Tokyo", "Dining",
        "1-15-1 Asakusa, Taito, Tokyo",
        "Asakusa Stn (3 min). User-flagged 'Gyukatsu!!!' — third Motomura branch, shortest line of the three."),
    "TORASUZU": ("Tokyo", "Dining",
        "1-39-12 Asakusa, Taito, Tokyo",
        "Asakusa Stn (4 min). Modern izakaya — pork tonpeiyaki + sake flight."),
    "Kobe beef Daia": ("Tokyo", "Dining",
        "Kaminarimon 1, Asakusa, Taito, Tokyo",
        "Asakusa Stn (1 min). Kobe-beef teppanyaki at Kaminarimon — same name twice in your list (east branch below)."),
    "Kura": ("Tokyo", "Dining",
        "2-2 Asakusa, Taito, Tokyo",
        "Asakusa Stn (3 min). Edo-style sushi-ya, 12 seats; reservation by phone only."),
    "LaVASARA CAFE&GRILL": ("Tokyo", "Dining",
        "1-35-3 Asakusa, Taito, Tokyo",
        "Asakusa Stn (4 min). Casual all-day brunch — a non-Japanese-food reset."),
    "ASAKUSA SUMO CLUB": ("Tokyo", "Cultural",
        "2-7-26 Nishi-Asakusa, Taito, Tokyo",
        "Tawaramachi Stn (3 min). Watch real sumo training + chanko lunch — book the 11am slot."),
    "Hibiya Park": ("Tokyo", "Sightseeing",
        "1 Hibiya Park, Chiyoda, Tokyo",
        "Hibiya Stn (1 min). Western-style park next to Imperial Palace — rose garden peaks late May."),
    "Ryogoku Kokugikan Sumo Arena": ("Tokyo", "Cultural",
        "1-3-28 Yokoami, Sumida, Tokyo",
        "Ryogoku Stn (1 min). May Basho ends mid-month; check Jun 3 18:00 booked Chanko Wanko dinner is right next door."),
    "Asahi Group Head Office Super Dry Hall": ("Tokyo", "Sightseeing",
        "1-23-1 Azumabashi, Sumida, Tokyo",
        "Asakusa Stn (5 min). 'Golden Flame' building — best photo from Azuma Bridge at dusk."),
    "Samurai Ninja Museum Asakusa Tokyo": ("Tokyo", "Cultural",
        "2-21-13 Asakusa, Taito, Tokyo",
        "Asakusa Stn (5 min). 90-min ninja experience — book online for ¥1000 off."),
    "Tempura Asakusa SAKURA": ("Tokyo", "Dining",
        "1-9-2 Asakusa, Taito, Tokyo",
        "Asakusa Stn (3 min). Lunch tendon ¥1500 — the conger eel set is the move."),
    "Ichiran Asakusa": ("Tokyo", "Dining",
        "1-37-7 Asakusa, Taito, Tokyo",
        "Asakusa Stn (5 min). Tonkotsu — Cody/JJ NOT safe (pork bone), Brady ok if 'no half-egg'."),
    "Kan'non-dōri": ("Tokyo", "Sightseeing",
        "Asakusa, Taito, Tokyo",
        "Asakusa Stn (3 min). East-west street perpendicular to Nakamise — quieter local shops."),
    "KOBE BEEF DAIA TEPPAN-YAKI KAMINARIMON EAST BRANCH": ("Tokyo", "Dining",
        "2-3-3 Kaminarimon, Taito, Tokyo",
        "Asakusa Stn (2 min). The east branch — newer, less crowded than the original."),
    "Nakamise Shopping Street": ("Tokyo", "Shopping",
        "1-36-3 Asakusa, Taito, Tokyo",
        "Asakusa Stn (1 min). 250m of Edo souvenir stalls — go before 9am for empty street photos."),
    "Sensō-ji": ("Tokyo", "Sightseeing",
        "2-3-1 Asakusa, Taito, Tokyo",
        "Asakusa Stn (5 min). Tokyo's oldest temple; light-up nightly until 23:00. STAMP RALLY: get the goshuin at the temple office."),
    "Ueno Ameyoko Shopping Street": ("Tokyo", "Shopping",
        "4 Ueno, Taito, Tokyo",
        "Ueno Stn (1 min). Open-air market under JR tracks — bargain street food + cosmetics."),
    "Shinobazu Pond": ("Tokyo", "Sightseeing",
        "Ueno Park, Taito, Tokyo",
        "Ueno Stn (5 min). Lotus pond; rent a swan boat ¥700/30 min."),
    "Ueno Park": ("Tokyo", "Sightseeing",
        "5-20 Uenokoen, Taito, Tokyo",
        "Ueno Stn (1 min). Park hub for 5 museums + zoo; sakura late, hydrangea early-June."),
    "Tokyo National Museum": ("Tokyo", "Sightseeing",
        "13-9 Uenokoen, Taito, Tokyo",
        "Ueno Stn (10 min). Honkan main hall — National Treasure katana room."),
    "Akihabara Electric Town": ("Tokyo", "Shopping",
        "1 Sotokanda, Chiyoda, Tokyo",
        "Akihabara Stn (1 min). Super Potato (5F) for retro; Yodobashi Akiba for new electronics."),
    "First Avenue Tokyo Station": ("Tokyo", "Shopping",
        "B1, 1-9-1 Marunouchi, Chiyoda, Tokyo",
        "Tokyo Stn (in-station). Character Street + Ramen Street + Okashi Land — all underground."),
    "Tokyo Station": ("Tokyo", "Transit",
        "1-9-1 Marunouchi, Chiyoda, Tokyo",
        "Tokyo Stn. Marunouchi side red-brick facade is the photo; depachika in Daimaru basement."),
    "Imperial Palace": ("Tokyo", "Sightseeing",
        "1-1 Chiyoda, Chiyoda, Tokyo",
        "Otemachi Stn (5 min). Free 75-min inner tour 10am/1:30pm Tue-Sat — register online."),
    "Meiji Jingu Gaien Ginkgo Avenue": ("Tokyo", "Sightseeing",
        "2-1 Kasumigaokamachi, Shinjuku, Tokyo",
        "Aoyama-itchome Stn (5 min). Off-season in spring (golden leaves are November), but a clean run/walk."),
    "Godzilla Head": ("Tokyo", "Sightseeing",
        "Hotel Gracery 8F, 1-19-1 Kabukicho, Shinjuku, Tokyo",
        "Shinjuku Stn (5 min). Free view from 8F deck of Hotel Gracery; roars hourly 12-8pm."),
    "Tokyo Metropolitan Government Building North Observation Deck": ("Tokyo", "Sightseeing",
        "2-8-1 Nishi-Shinjuku, Tokyo",
        "Tochomae Stn (1 min). FREE 202m deck — go at sunset for Fuji silhouette on clear day."),
    "Takeshita Shopping Street": ("Tokyo", "Shopping",
        "1-17 Jingumae, Shibuya, Tokyo",
        "Harajuku Stn (1 min). Crepe row + thrift; weekday morning > Sunday."),
    "Meiji Jingu": ("Tokyo", "Sightseeing",
        "1-1 Yoyogikamizonocho, Shibuya, Tokyo",
        "Harajuku Stn (1 min). Forest shrine — first prayer of day at 5am-ish."),
    "Yoyogi Park": ("Tokyo", "Sightseeing",
        "2-1 Yoyogikamizonocho, Shibuya, Tokyo",
        "Harajuku Stn (3 min). Sunday rockabilly dancers near Harajuku gate."),
    "Shibuya Sky": ("Tokyo", "Sightseeing",
        "Shibuya Scramble Square 45F, 2-24-12 Shibuya, Tokyo",
        "Shibuya Stn (1 min). Book online for ¥2200 sunset slot — sells out 2 weeks ahead."),
    "Shibuya Crossing": ("Tokyo", "Sightseeing",
        "2 Dogenzaka, Shibuya, Tokyo",
        "Shibuya Stn Hachiko exit. Best overhead view: Mag's Park or Starbucks Tsutaya 2F."),
    "Mori Art Museum": ("Tokyo", "Sightseeing",
        "Roppongi Hills Mori Tower 53F, 6-10-1 Roppongi, Minato, Tokyo",
        "Roppongi Stn (3 min). Includes Tokyo City View — open till 22:00 Tue-Sun."),
    "Roppongi Hills - Tokyo City View": ("Tokyo", "Sightseeing",
        "Mori Tower 52F, 6-10-1 Roppongi, Minato, Tokyo",
        "Roppongi Stn (3 min). Combo ticket w/ Mori Art saves ¥500."),
    "Tokyo Tower": ("Tokyo", "Sightseeing",
        "4-2-8 Shibakoen, Minato, Tokyo",
        "Akabanebashi Stn (5 min). Original deck cheaper than Skytree; 7pm light-up = orange glow."),
    "GINZA SIX": ("Tokyo", "Shopping",
        "6-10-1 Ginza, Chuo, Tokyo",
        "Ginza Stn (3 min). Rooftop garden free; B2 depachika for omiyage."),
    "Kabuki-za": ("Tokyo", "Cultural",
        "4-12-15 Ginza, Chuo, Tokyo",
        "Higashi-Ginza Stn (1 min). Single-act tickets ¥1000-¥2500 sold day-of from side window."),
    # --- Hakone ---
    "Lake Ashi": ("Hakone", "Sightseeing",
        "Hakone-machi, Ashigarashimo, Kanagawa",
        "Hakone-Yumoto Stn + bus 40 min. Pirate-ship cruise + Hakone Shrine torii photo."),
    "Tōgendai Observation Deck": ("Hakone", "Sightseeing",
        "Hakone-machi, Kanagawa",
        "Togendai Stn (ropeway). Grab a sansho-mochi at the kiosk before the ropeway."),
    "Sōunzan Station": ("Hakone", "Transit",
        "1300 Gora, Hakone, Kanagawa",
        "Sounzan Stn. Switch from Hakone Tozan cable car to ropeway — 10-min connection."),
    "Gora Station": ("Hakone", "Transit",
        "1300 Gora, Hakone, Kanagawa",
        "Gora Stn. Last stop on the switchback railway — onsen mochi shops at the exit."),
    # --- Osaka ---
    "Spark": ("Osaka", "Nightlife",
        "1-7-15 Sonezaki, Kita, Osaka",
        "Higashi-Umeda Stn (3 min). Hidden listening bar, vinyl jazz; ¥1000 entry."),
    "Shinsekai": ("Osaka", "Sightseeing",
        "Ebisuhigashi, Naniwa, Osaka",
        "Dobutsuen-mae Stn (1 min). Retro 1900s neighborhood + Tsutenkaku tower; kushikatsu street."),
    "Tennoji Park": ("Osaka", "Sightseeing",
        "5-55 Chausuyamacho, Tennoji, Osaka",
        "Tennoji Stn (3 min). Free park + paid Keitakuen garden ¥150."),
    "Magic Cafe & Bar Shinsekai": ("Osaka", "Nightlife",
        "Janjan Yokocho, Naniwa, Osaka",
        "Dobutsuen-mae Stn (3 min). Close-up magic w/ ¥1500 cover; English-friendly."),
    "Namba City": ("Osaka", "Shopping",
        "5-1-60 Namba, Chuo, Osaka",
        "Namba Stn (1 min). 5-floor mall above Namba Stn; B2 depachika is excellent."),
    # --- Kyoto Sightseeing / Dining ---
    "Hirobun": ("Kyoto", "Dining",
        "87 Kuramakibunecho, Sakyo, Kyoto",
        "Kibune-guchi Stn + bus. Kawadoko nagashi-somen May-Sep — arrive 9am for same-day numbered ticket. Brady ok, Cody/JJ ask kombu broth."),
    "Arashiyama Monkey Park Iwatayama": ("Kyoto", "Sightseeing",
        "8 Arashiyama-Genrokuyamacho, Nishikyo, Kyoto",
        "Hankyu Arashiyama Stn (10 min walk). 20-min uphill hike — best Kyoto skyline view."),
    "Hozugawa River Boat Ride (Hozugawa Kudari)": ("Kyoto", "Cultural",
        "2 Shimonakajima, Kameoka, Kyoto",
        "Kameoka Stn (10 min). BOOKED May 26 11:00 — 2hr boat to Arashiyama, then Itsuki Chaya 13:45."),
    "MUSIC BAR universe -GION-": ("Kyoto", "Nightlife",
        "B1, 277-22 Gionmachi-Minamigawa, Higashiyama, Kyoto",
        "Gion-Shijo Stn (5 min). Geisha-district cocktail bar; ¥1500 cover."),
    "Pop": ("Kyoto", "Nightlife",
        "Sanjo-Kawaramachi, Kyoto",
        "Sanjo Stn (3 min). Tiny standing bar — locals only feel; check Google for hours."),
    "VINYL RECORD MUSIC BAR 『P.M.SOUNDS KYOTO』": ("Kyoto", "Nightlife",
        "Kiyamachi-dori, Nakagyo, Kyoto",
        "Sanjo Stn (3 min). Vinyl-only soul/funk; ¥1500 + 1 drink."),
    # --- Outliers ---
    "Jigokudani Yaen-Koen": ("Nagano", "Sightseeing",
        "6845 Yamanouchi-machi, Shimotakai, Nagano",
        "Yudanaka Stn + bus. Snow Monkeys — but May-Jun water is cool, fewer monkeys bathe; better as bookmark for next trip."),
    "Tōdai-ji": ("Nara", "Sightseeing",
        "406-1 Zoshicho, Nara",
        "Kintetsu-Nara Stn + bus 10 min. Great Buddha hall — squeeze through the 'Buddha's nostril' pillar for luck."),
    "Amanohashidate": ("Kyoto-North", "Sightseeing",
        "Monju, Miyazu, Kyoto",
        "Amanohashidate Stn. Day-trip from Kyoto (2.5hr); the matanozoki upside-down view is the gimmick."),
    "Mount Kinugasa": ("Kyoto", "Sightseeing",
        "Kinugasayama, Kita, Kyoto",
        "Kinkakuji-mae bus stop. Hill behind Kinkaku-ji — quiet hike loop."),
    "Ryōan-ji": ("Kyoto", "Sightseeing",
        "13 Ryoanji Goryonoshitacho, Ukyo, Kyoto",
        "Bus 50 from Kyoto Stn. Famous 15-stone rock garden — go 8am to count all 15."),
    "Nishiki Market": ("Kyoto", "Shopping",
        "Nishikikoji-dori, Nakagyo, Kyoto",
        "Karasuma Stn (5 min). Kyoto's kitchen — Aritsugu knives + Konnamonja yuba shop. STAMP RALLY: ask for the market passport."),
    "Kiyomizu-dera": ("Kyoto", "Sightseeing",
        "1-294 Kiyomizu, Higashiyama, Kyoto",
        "Kiyomizu-Gojo Stn (15 min walk). Wooden stage temple; arrive by 7am to beat tour buses."),
    "Hozukyo Observatory": ("Kyoto", "Sightseeing",
        "Sagakameokahonmichi, Ukyo, Kyoto",
        "Saga-Arashiyama Stn (5 min walk). Free deck above Hozugawa rapids — view your boat ride from above."),
    "Arashiyama": ("Kyoto", "Sightseeing",
        "Arashiyama, Ukyo, Kyoto",
        "Saga-Arashiyama Stn. The bamboo grove at 7am is the move — Togetsukyo bridge by 9am."),
    "Fushimi Inari Taisha": ("Kyoto", "Sightseeing",
        "68 Fukakusa Yabunouchicho, Fushimi, Kyoto",
        "Inari Stn (1 min). 10,000 torii — climb to Yotsutsuji (30 min) then bail; whole loop is 2hr."),
    "Kinkaku-ji": ("Kyoto", "Sightseeing",
        "1 Kinkakujicho, Kita, Kyoto",
        "Bus 101 from Kyoto Stn. Golden Pavilion — opens 9am, expect crowds; pair with Ryoan-ji."),
    "Osaka Castle": ("Osaka", "Sightseeing",
        "1-1 Osakajo, Chuo, Osaka",
        "Tanimachi-yonchome Stn (10 min). Castle museum ¥600 — outer park free; sakura March-April."),
    "American Village": ("Osaka", "Shopping",
        "Nishi-Shinsaibashi, Chuo, Osaka",
        "Shinsaibashi Stn (5 min). Streetwear thrift mecca — Big Step mall is the anchor."),
    "Tonbori River Walk": ("Osaka", "Sightseeing",
        "Dotonbori, Chuo, Osaka",
        "Namba Stn (3 min). Glico sign at night > day; takoyaki at Wanaka."),
    "Deer Park": ("Nara", "Sightseeing",
        "Kasugano-cho, Nara",
        "Kintetsu-Nara Stn (5 min). 1200 free-roaming deer — bow before they bow back; shika-senbei ¥200."),
    "Nintendo Museum": ("Kyoto", "Cultural",
        "56 Ogura-cho, Uji, Kyoto",
        "Ogura Stn (5 min). Lottery ticket system — apply online 3 mo ahead; if no luck, gift shop is walk-in."),
    "Ginkaku-ji": ("Kyoto", "Sightseeing",
        "2 Ginkakujicho, Sakyo, Kyoto",
        "Bus 5 from Kyoto Stn. Silver Pavilion + Philosopher's Path — combo with Nanzen-ji on the same Sakyo loop."),
    "Kyoto Imperial Palace": ("Kyoto", "Sightseeing",
        "3 Kyotogyoen, Kamigyo, Kyoto",
        "Imadegawa Stn (5 min). Free entry, ID required; 60-min self-guided loop."),
    "Kyoto Gyoen National Garden": ("Kyoto", "Sightseeing",
        "3 Kyotogyoen, Kamigyo, Kyoto",
        "Imadegawa Stn (5 min). Park surrounding the palace — plum + cherry walk."),
    "Nijō Castle": ("Kyoto", "Sightseeing",
        "541 Nijojocho, Nakagyo, Kyoto",
        "Nijojo-mae Stn (1 min). Nightingale-floor shogun residence; ¥1300 incl. Ninomaru."),
    "燕申堂": ("Kyoto", "Cafe",
        "Teramachi-dori, Nakagyo, Kyoto",
        "Karasuma-Oike Stn (5 min). Tucked tea-and-sweets house — yokan + matcha set ~¥1500."),
    "Higashi Hongan-ji Temple": ("Kyoto", "Sightseeing",
        "Karasuma-dori Shichijo-agaru, Shimogyo, Kyoto",
        "Kyoto Stn (5 min walk). Free entry — closest major temple to the station, wood-rope made of donated hair."),
    "Kawaramachi-dori St": ("Kyoto", "Shopping",
        "Kawaramachi-dori, Nakagyo, Kyoto",
        "Kawaramachi Stn. Main shopping artery — Loft + Tower Records + arcades."),
    "Samurai Kembu Theater": ("Kyoto", "Cultural",
        "35 Higashinotoincho, Higashiyama, Kyoto",
        "Sanjo Stn (5 min). 90-min sword-dance performance + try-it experience."),
    "Kamo River Noryo-Yuka": ("Kyoto", "Dining",
        "Pontocho Riverside, Nakagyo, Kyoto",
        "Sanjo Stn (3 min). May-Sep riverside dining decks — book a Pontocho restaurant w/ yuka platform."),
    "The Flower Corridor": ("Kyoto", "Sightseeing",
        "Kawabata-dori, Higashiyama, Kyoto",
        "Gion-Shijo Stn (3 min). Gion's flower-name street — geiko commute corridor at dusk."),
    "Shirakawa Canal": ("Kyoto", "Sightseeing",
        "Gion Shirakawa, Higashiyama, Kyoto",
        "Sanjo Keihan Stn (5 min). Willow-lined stream — most photogenic Kyoto block, 7am best."),
    "Yasaka Pagoda Photo Spot": ("Kyoto", "Sightseeing",
        "Yasaka-dori, Higashiyama, Kyoto",
        "Higashiyama Stn (10 min). The iconic uphill pagoda shot — earlier than 6am for empty street."),
    "Ninenzaka": ("Kyoto", "Sightseeing",
        "Masuyacho, Higashiyama, Kyoto",
        "Higashiyama Stn (10 min). Stone steps to Kiyomizu — Starbucks tatami branch is here."),
    "花見小路（南側）": ("Kyoto", "Sightseeing",
        "Hanamikoji South, Higashiyama, Kyoto",
        "Gion-Shijo Stn (3 min). South Hanamikoji — quieter than the north geisha street."),
    "Hanamikoji Street": ("Kyoto", "Sightseeing",
        "Hanamikoji-dori, Higashiyama, Kyoto",
        "Gion-Shijo Stn (3 min). Geiko spotting at dusk — DO NOT photograph maiko (¥10k fine)."),
    "Chionin Temple": ("Kyoto", "Sightseeing",
        "400 Rinkacho, Higashiyama, Kyoto",
        "Higashiyama Stn (5 min). Japan's largest wooden gate (Sanmon); free outer grounds."),
    "Nanzen-ji": ("Kyoto", "Sightseeing",
        "Nanzenji Fukuchicho, Sakyo, Kyoto",
        "Keage Stn (5 min). Aqueduct + zen garden combo; chain it with Philosopher's Path to Ginkaku-ji."),
    # --- Himeji / Hiroshima / Miyajima ---
    "Himeji Castle": ("Himeji", "Sightseeing",
        "68 Honmachi, Himeji, Hyogo",
        "Himeji Stn (15 min walk). White Heron Castle — buy combo Castle+Kokoen ¥1050; arrive 9am."),
    "Hiroshima National Peace Memorial Hall for the Atomic Bomb Victims": ("Hiroshima", "Sightseeing",
        "1-6 Nakajimacho, Naka, Hiroshima",
        "Genbaku-Dome Mae tram (3 min). Free; quiet underground memorial — pair with Peace Museum."),
    "Atomic Bomb Dome": ("Hiroshima", "Sightseeing",
        "1-10 Otemachi, Naka, Hiroshima",
        "Genbaku-Dome Mae tram (1 min). Free outdoor view 24/7; sunset light is the photo."),
    "Hiroshima Castle": ("Hiroshima", "Sightseeing",
        "21-1 Motomachi, Naka, Hiroshima",
        "Kamiyacho-nishi tram (10 min walk). Reconstructed castle — keep ¥370 inside, gardens free."),
    "Itsukushima Jinja": ("Miyajima", "Sightseeing",
        "1-1 Miyajimacho, Hatsukaichi, Hiroshima",
        "Miyajima ferry from Miyajima-guchi (10 min). Floating torii — check tide chart, high tide AM is the shot."),
    # --- Kumamoto ---
    "Tomiaimachi Minamitanoshiri": ("Kumamoto", "Cultural",
        "Tomiaimachi Minamitanoshiri, Minami-ku, Kumamoto",
        "User pinned: 'Sachiko's neighborhood' — drive-by visit on the Kumamoto leg."),
    # --- Hotels ---
    "Solaria Nishitetsu Hotel Kagoshima": ("Kagoshima", "Hotel",
        "1-3 Yamanokuchicho, Kagoshima 892-0844",
        "Tenmonkan-dori tram (1 min). Booked. Top-floor onsen w/ Sakurajima view."),
    "CANDEO HOTELS Kumamoto Shinshigai": ("Kumamoto", "Hotel",
        "1-2-1 Shimotorimachi, Chuo, Kumamoto",
        "Tsuruyahyakkaten-mae tram (3 min). Booked. Sky spa on roof — open till midnight."),
    "THE KNOT HIROSHIMA": ("Hiroshima", "Hotel",
        "7-13 Mikawacho, Naka, Hiroshima",
        "Hatchobori tram (5 min). Booked. Walk to Peace Park in 15 min."),
    "Hotel Resol Kyoto Shijo Muromachi": ("Kyoto", "Hotel",
        "Shijo Muromachi, Shimogyo, Kyoto",
        "Karasuma Stn (3 min). Booked. Right between Nishiki Market + Karasuma subway."),
    "nol hakone myojindai": ("Hakone", "Hotel",
        "1320-862 Gora, Hakone, Kanagawa",
        "Gora Stn + 5 min taxi. Booked. Designer ryokan w/ private onsen rooms; kaiseki is a Brady-egg-free request."),
    "THE GATE HOTEL Kaminarimon by HULIC": ("Tokyo", "Hotel",
        "2-16-11 Kaminarimon, Taito, Tokyo",
        "Asakusa Stn (1 min). Booked. Rooftop bar overlooks Senso-ji."),
}

# ---- Hidden gem additions (5, spread across the route) ----
GEMS = [
    ("Kissaten Niki Niki",
        ("Kagoshima", "Cafe",
         "1-2 Higashisengokucho, Kagoshima 892-0842",
         "Tenmonkan-dori tram (3 min). 1970s kissaten — siphon coffee + thick cream-soda; opens 8am, perfect pre-Sakurajima warmup. (Hidden gem · Kissaten)")),
    ("Andersen Hiroshima Depachika",
        ("Hiroshima", "Shopping",
         "7-1 Hondori, Naka, Hiroshima 730-0035",
         "Hondori tram (2 min). Hiroshima's depachika-style bakery hall — momiji-manju at Nishiki-do, oysters fresh upstairs. (Hidden gem · Depachika)")),
    ("Smart Coffee",
        ("Kyoto", "Cafe",
         "537 Tenshocho, Nakagyo, Kyoto 604-8017",
         "Sanjo Stn (3 min). 1932 kissaten — order the hotcake, served on real china; cash only, no laptops. (Hidden gem · Kissaten)")),
    ("Hakone Open-Air Museum Stamp Walk",
        ("Hakone", "Cultural",
         "1121 Ninotaira, Hakone, Kanagawa 250-0407",
         "Chokoku-no-Mori Stn (1 min). Pick up the Hakone Free Pass stamp book and collect 7 station stamps along the loop. (Hidden gem · Stamp Rally)")),
    ("Isetan Shinjuku Depachika",
        ("Tokyo", "Shopping",
         "3-14-1 Shinjuku, Shinjuku, Tokyo 160-0022",
         "Shinjuku-sanchome Stn (1 min). Tokyo's reigning depachika — hit Toraya yokan, Nadaman bento, Pierre Hermé before 7pm half-off. (Hidden gem · Depachika)")),
]

# ---- Read input ----
src = "/home/user/workspace/Japan-2026.csv"
out_csv = "/home/user/workspace/Japan-itinerary/japan2026-mymaps.csv"
out_md = "/home/user/workspace/Japan-itinerary/japan2026-mymaps.md"

rows = []
missing = []

with open(src, encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for r in reader:
        title = r.get("Title", "").strip()
        if not title:
            continue
        url = r.get("URL", "").strip()
        user_comment = r.get("Note", "").strip()
        if title in DB:
            city, cat, addr, note = DB[title]
        else:
            missing.append(title)
            city, cat, addr, note = ("Japan", "Sightseeing", "", "")
        # Preserve user's existing comment
        if user_comment:
            note = f"\"{user_comment}\" — {note}"
        meta = CATEGORY_META[cat]
        rows.append({
            "Name": title,
            "Address": addr,
            "Category": cat,
            "Note": note,
            "Emoji": meta["emoji"],
            "City": city,
            "Color": meta["color"],
            "MapsURL": url,
        })

# Append hidden gems
for name, (city, cat, addr, note) in GEMS:
    meta = CATEGORY_META[cat]
    rows.append({
        "Name": name,
        "Address": addr,
        "Category": cat,
        "Note": note,
        "Emoji": meta["emoji"],
        "City": city,
        "Color": meta["color"],
        "MapsURL": "",
    })

# ---- CSV out (Google My Maps format) ----
os.makedirs(os.path.dirname(out_csv), exist_ok=True)
with open(out_csv, "w", encoding="utf-8", newline="") as f:
    w = csv.DictWriter(f, fieldnames=["Name","Address","Category","Note","Emoji","City","Color","MapsURL"])
    w.writeheader()
    w.writerows(rows)

# ---- Markdown table out ----
def md_escape(s):
    return (s or "").replace("|", "\\|").replace("\n", " ")

CITY_ORDER = ["Kagoshima","Kumamoto","Hiroshima","Miyajima","Himeji","Osaka","Nara","Kyoto","Kyoto-North","Nagano","Hakone","Atami","Izu","Tokyo","Japan"]
def city_key(r):
    c = r["City"]
    return CITY_ORDER.index(c) if c in CITY_ORDER else 999

CAT_ORDER = ["Hotel","Sightseeing","Cultural","Dining","Cafe","Shopping","Nightlife","Transit"]
def cat_key(r):
    return CAT_ORDER.index(r["Category"]) if r["Category"] in CAT_ORDER else 99

rows_sorted = sorted(rows, key=lambda r: (city_key(r), cat_key(r), r["Name"]))

lines = []
lines.append("# Japan 2026 — Google My Maps Concierge Set")
lines.append("")
lines.append(f"**{len(rows)} places** ({len(rows)-len(GEMS)} from your list + {len(GEMS)} hidden gems) · grouped by city, color-coded by category for re-import.")
lines.append("")
lines.append("**Category legend:** 🍜 Dining (red) · ☕ Cafe/Kissaten (brown) · 🏯 Sightseeing (blue) · 🛍️ Shopping (green) · 🏨 Hotel (purple) · 🌃 Nightlife (pink) · 🎌 Cultural (gold) · 🚉 Transit (gray)")
lines.append("")
last_city = None
for r in rows_sorted:
    if r["City"] != last_city:
        lines.append("")
        lines.append(f"## {r['City']}")
        lines.append("")
        lines.append("| Emoji | Name | Category | Address | Note |")
        lines.append("|:-:|:--|:--|:--|:--|")
        last_city = r["City"]
    lines.append(f"| {r['Emoji']} | **{md_escape(r['Name'])}** | {r['Category']} | {md_escape(r['Address'])} | {md_escape(r['Note'])} |")

with open(out_md, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Wrote {out_csv}")
print(f"Wrote {out_md}")
print(f"Total rows: {len(rows)}")
print(f"Missing from DB ({len(missing)}):")
for m in missing:
    print(f"  - {m}")
